# Generated by Django 4.2.4 on 2023-10-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=120, verbose_name='Recipe name')),
                ('preparation', models.TextField(blank=True, verbose_name='Preparations')),
                ('recipe_img', models.ImageField(blank=True, null=True, upload_to='recipes', verbose_name='recipe Image')),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='Food Tags')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
    ]
